Updated fixup_user method to remove "<<>>" in user commit message which causes fatal error
error: fatal: Missing > in ident string: Filip Bucek <<>> <devnull@localhost> 1441788980 +0200
info: No idea why it was in commit message ( maybe some mistake )